version: '3.8'

services:
  app:
    build: .
    container_name: test-logique
    ports:
      - "3000:3000"
    environment:
      APP_ENV: "development"
      APP_URL: "http://localhost:3000"
      API_KEY: "logique"
      APP_PORT: 3000
      APP_SWAGGER_USERNAME: "username"
      APP_SWAGGER_PASSWORD: "password"
      DB_HOST: "db"  # Use the service name for Docker networking
      DB_PORT: "3306"
      DB_USERNAME: "root"
      DB_PASSWORD: "gontang01"
      DB_DATABASE: "test_logique"
    command: "npx ts-node src/index.ts"
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "gontang01"
      MYSQL_DATABASE: "test_logique"
    ports:
      - "3306:3306"